#!/bin/bash

# This script helps you identify the Railway URLs you need

echo "🔍 Railway Configuration Helper"
echo "================================"
echo ""
echo "You need to find TWO URLs in your Railway dashboard:"
echo ""
echo "1️⃣  SERVER URL (Node.js/Express service)"
echo "   - Click on 'server' service in Railway"
echo "   - Go to 'Deployments' or 'Settings' → 'Domains'"
echo "   - Copy the URL (e.g., https://server-production-XXXX.up.railway.app)"
echo ""
echo "2️⃣  CLIENT URL (React/Vite service)" 
echo "   - Click on 'client' service in Railway"
echo "   - Go to 'Deployments' or 'Settings' → 'Domains'"
echo "   - Copy the URL (e.g., https://party-zala.up.railway.app)"
echo ""
echo "================================"
echo "Then set these environment variables:"
echo ""
echo "📦 CLIENT Service Variables:"
echo "   VITE_API_URL=[YOUR-SERVER-URL]"
echo ""
echo "📦 SERVER Service Variables:"
echo "   CLIENT_ORIGIN=[YOUR-CLIENT-URL]"
echo ""
echo "================================"
echo "After setting the variables:"
echo "1. Save the variables in Railway"
echo "2. REDEPLOY the CLIENT service"
echo "3. Wait 2-3 minutes"
echo "4. Test your app"
echo ""
